### PR TITLE
Further map devt

### PR DESCRIPTION
**Pull request by t2n**
added zooming, hovering on people with tooltip, motion + fixed webpack removing .gitkeep from dist

### CODE REVIEW

**Comment by karolsojko** [comment]
does this PR fix this issue: https://github.com/x-team/x-map-2/issues/3 ?

**Comment by t2n** [comment]
@karolsojko it doesn't, I will add source maps to make investigation easier

**Comment by t2n** [comment]
@karolsojko it potentially does now

**Comment by karolsojko** [comment]
Fixes #3

**Pull request merged**
